### ISSUE TITLE
CONFIG command enhancements and additional config reference file

### ISSUE THREAD

**Issue by Wengier** [Wengier/dosbox-x-wiki#10]
I have enhanced the CONFIG command (and Configuration Tool) which will now save common + modified advanced config options by default. The -all command-line option (or the new "Save all options to the configuration file" checkbox in Configuration Tool) will let DOSBox-X save all config options (both common and advanced config options) to the config file. A new -mod command-line option is added to the CONFIG command to save modified config options only. Furthermore, there are now two config reference files, named dosbox-x.reference.conf and dosbox-x.reference.full.conf respectively. Unlike the dosbox-x.reference.full.conf file, the new dosbox-x.commonref.conf file will contain common options (the exact same config options when "Show advanced options" is not checked in the Configuration Tool). On the other hand, the dosbox-x.reference.full.conf file will include all config options (both common and advanced options) just as before.

**Comment by Wengier** [comment]
The size of the new dosbox-x.reference.conf is much smaller than dosbox-x.reference.full.conf, which makes it easier for new users etc to navigate. Both are auto-generated and can be viewed in the repository:

https://github.com/joncampbell123/dosbox-x/blob/master/dosbox-x.reference.conf

https://github.com/joncampbell123/dosbox-x/blob/master/dosbox-x.reference.full.conf

**Comment by Wengier** [comment]
@rderooy I think you usually post config files with only changed config options and without remarks. For this I have also added  -norem command-line option to the CONFIG command, so with ```CONFIG -mod -norem``` I think you will get exactly what you want from a full config file.

**Comment by rderooy** [comment]
@Wengier That is a great option for troubleshooting to quickly know what settings have been changed from default!

And indeed, the Win9x configs on the wiki, only contain the changes from default to keep it short and to the point.
