### ISSUE TITLE
cputype table

### ISSUE THREAD

**Issue by rderooy** [Wengier/dosbox-x-wiki#11]
@Wengier @joncampbell123

Based on this: https://www.vogons.org/viewtopic.php?f=32&t=77296&p=905717#p905717

I thought it a good idea to make a similar table for dosbox-x. So I made this draft:
https://github.com/Wengier/dosbox-x-wiki/wiki/Guide%3ACPU-Type-settings-in-DOSBox%E2%80%90X

Note: the above page is not currently linked from the wiki as it is a incomplete draft. I tried to use the table from vogons user Delfino Furioso and extend it to dosbox-x, but obviously there have been quite a lot of changes to dosbox-x in the emulated CPU options. In particular, I don't know what the difference is between 486 and 486old. I'm guessing that 486old is the implementation inherited from vanilla dosbox, and 486 is a new implementation?

One of the problems is one of layout. asciidoc allows more options than md, but still it does not look very good and the table is far too wide for the wiki.

**Comment by Wengier** [comment]
@rderooy Thanks for making a table for CPU types. I certainly think @joncampbell123 is knowledge about CPU-related things.

Also, I think you can probably separate the table into two, e.g. one from 8086 to 386, and the other from 486 onwards. This will hopefully solve the issue with the table being too wide for the Wiki.

**Comment by rderooy** [comment]
@Wengier I moved the table to https://github.com/Wengier/dosbox-x-wiki/wiki/Guide:CPU-settings-in-DOSBox%E2%80%90X

I also split the table as you suggested. Have a look.

The original table is still there, but can be removed if you guys think this is better.

**Comment by Wengier** [comment]
@rderooy The new tables certainly look better - good job! On the other hand, @joncampbell123 is certainly more knowledgeable about the CPU technical details and may give further feedback if any issues are found.
