### ISSUE TITLE
mTCP and towel.blinkenlights.nl

### ISSUE THREAD

**Issue by jadasse** [Wengier/dosbox-x-wiki#13]
How do I connect to towel.blinkenlights.nl alike so in https://www.wikihow.com/Watch-Movies-Using-Telnet in mTCP ?

**Comment by rderooy** [comment]
The mTCP package includes a telnet.exe client, so make sure mTCP works and try
```
telnet towel.blinkenlights.nl
```

**Comment by jadasse** [comment]
oops wrong page lol

**Comment by jadasse** [comment]
*github page

**Comment by jadasse** [comment]
I might as well make the most of it, I guess:

it gives me:
mTCP: Warning - trailing whitespace detected on line 23 of the config file.

Your DHCP lease expires in less than 3600 seconds! Please run dhcp.exe

**Comment by jadasse** [comment]
I posted my issue where it should belong :)
