### ISSUE TITLE
PING google.com doesn't work

### ISSUE THREAD

**Issue by jadasse** [Wengier/dosbox-x-wiki#14]
it gives me:
mTCP: Warning - trailing whitespace detected on line 23 of the config file.

Your DHCP lease expires in less than 3600 seconds! Please run dhcp.exe

However, when I type in DHCP google.com, it gives me:
unknown option: google.com

dhcp [options]

options:
 -help
 -retries <n> Retry n times before giving up
 -timeout <n> Set timeout for each attempt to n seconds
 -packetstats Show packet statistics at the end

What do I do?

**Comment by Wengier** [comment]
Can you post your config file so that we can take a look at? Thanks.
