### ISSUE TITLE
3dfx voodoo glide pass-through wiki updated

### ISSUE THREAD

**Issue by rderooy** [Wengier/dosbox-x-wiki#16]
I have updated the Win95, Win98 and 3dfx voodoo wiki pages to add that it can be used with Win9x games.

**Comment by Wengier** [comment]
Thanks! I have transfer the Wiki contents accordingly.

**Comment by Wengier** [comment]
@rderooy By the way, a macOS user wishes to share his findings about printing. You can see if there is anything below that may be useful:

dosbox-x.conf:

[parallel]
parallel1 = file file:/Users/tom/Documents/Print1.txt  timeout:10 openwith:'/Users/tom/Documents/Matula/lpt1.py'


and my lpt1.py playground
<lpt1.py>



maybe of interest in there:

Change encoding: 
infile = open(printer_datei, "r",encoding="cp437")
inhalt = infile.read()
....
outfile = open(printer_tmp, "w",encoding="utf8")
outfile.write(inhalt)
....

create PDF of the text file
os.system("lpr -P PDFwriter '" + printer_tmp + "'")
(PDFwriter is the name of a PDF Printer https://sourceforge.net/projects/pdfwriterformac/ )
