### ISSUE TITLE
2 issues: Line Breaks and disappearing characters in Clipboard

### ISSUE THREAD

**Issue by XYwriter** [Wengier/dosbox-x-wiki#17]
Pardon me if this has been raised before and I can't find it.

I am running XYwrite 4 in DosBox-X-App, Edward Mendelson's Mac port of DosBox for word processors.

I Select in XYwrite and send to the clipboard with a key mapped in DosBox (CTRL-Z)

When I paste that selection into Mac's TextEdit or a Google Doc, sometimes I don't get the full selection. The last line or so is cut off. I can't figure out whether there is a character limit--it happens randomly with paragraph-long or page-long selections.

Also, when I copy the clipped text from XY4 iinto TextEdit or a Google Doc, it shows line breaks (left arrow) and paragraph breaks (circle and musical note).  I can delete them but I have to do that manually. Is there a way to keep the breaks but make the arrows/circle/note not show? 

I have tried using the online Line Breaks Remover tool at textfixer.com, and it removes the line breaks but retains the circle/musical note paragraph breaks.

Thanks. I am very grateful for DosBox-X.

**Comment by rderooy** [comment]
This is not the right place for this. This is our draft wiki for the next release. Please go to the main dosbox-x issues page instead.
https://github.com/joncampbell123/dosbox-x/issues
