### ISSUE TITLE
How to contribute to the wiki?

### ISSUE THREAD

**Issue by dbjh** [Wengier/dosbox-x-wiki#18]
I would like to contribute to the wiki (actually http://dosbox-x.com/wiki/) in order to explain some functionality that was recently accepted in https://github.com/joncampbell123/dosbox-x. I am relatively new to Git and GitHub. How do I go about this?

**Comment by rderooy** [comment]
@dbjh unless Wengier gives you access, the only thing you can do is create a PR against this repo.

Since Wengier is not very active any longer, I should perhaps move this to my personal space on github, such that I can give you access myself. But I don't have time for that right this moment.

**Comment by dbjh** [comment]
Thanks for the quick response.

Right, create a PR. The thing is that the wiki is in the wiki section of this project, not in the code section (project repo). I cloned https://github.com/Wengier/dosbox-x-wiki.wiki.git locally, but I was wondering whether I can create a PR if I push that to my GitHub page. I mean, GitHub doesn't know that the repos are related and the wiki seems to be treated differently.

Of course I don't have to do it through GitHub. I could also create a good old unified patch and make that available to you. I intend to only modify one section of the documentation.

**Comment by dbjh** [comment]
Thank you for the invitation. I have a couple of follow-up questions, but it would be better to ask them in private. How can we communicate without one of us having to reveal his e-mail address to the rest of the world?

**Comment by rderooy** [comment]
You can join the Discord channel. Although I don't always find time in the evening to join.

https://discord.gg/s5pP8F6j
