### ISSUE TITLE
Wiki images incorporated

### ISSUE THREAD

**Issue by Wengier** [Wengier/dosbox-x-wiki#2]
@rderooy I have already incorporated the following new images you uploaded to this repository into the Wiki /images directory (in addition to the ones you uploaded earlier):

https://github.com/Wengier/dosbox-x-wiki/wiki/images/MS-DOS:PC-DOS_2.0_BOOT_FDD.png
https://github.com/Wengier/dosbox-x-wiki/wiki/images/MS-DOS:PC-DOS_2.0_BOOT_HDD.png
https://github.com/Wengier/dosbox-x-wiki/wiki/images/MS-DOS:PC-DOS_2.0_FDISK.png
https://github.com/Wengier/dosbox-x-wiki/wiki/images/MS-DOS:PC-DOS_2.0_FDISK2.png
https://github.com/Wengier/dosbox-x-wiki/wiki/images/MS-DOS:PC-DOS_2.0_FORMAT.png
https://github.com/Wengier/dosbox-x-wiki/wiki/images/MS-DOS:PC-DOS_2.0_IMGMAKE.png

EDIT: These are now deleted as they are no longer necessary.

**Comment by rderooy** [comment]
To be honest, I think I will not use those as I decided to merge DOS 2.x with DOS 3.x as there is very little difference between them. I did however just upload some MS-DOS 4.01 images that are referenced.

**Comment by Wengier** [comment]
@rderooy That is fine. I have already deleted the DOS 2.x images from the Wiki /images directory, and then move the following MS-DOS 4.01 images there:

https://github.com/Wengier/dosbox-x-wiki/wiki/images/MS-DOS:MS-DOS_4.01_BOOT_HDD2.png
https://github.com/Wengier/dosbox-x-wiki/wiki/images/MS-DOS:MS-DOS_4.01_DOSSHELL.png
https://github.com/Wengier/dosbox-x-wiki/wiki/images/MS-DOS:MS-DOS_4.01_INSTALLER10.png
https://github.com/Wengier/dosbox-x-wiki/wiki/images/MS-DOS:MS-DOS_4.01_INSTALLER11.png
https://github.com/Wengier/dosbox-x-wiki/wiki/images/MS-DOS:MS-DOS_4.01_INSTALLER2.png
https://github.com/Wengier/dosbox-x-wiki/wiki/images/MS-DOS:MS-DOS_4.01_INSTALLER3.png
https://github.com/Wengier/dosbox-x-wiki/wiki/images/MS-DOS:MS-DOS_4.01_INSTALLER4.png
https://github.com/Wengier/dosbox-x-wiki/wiki/images/MS-DOS:MS-DOS_4.01_INSTALLER5.png
https://github.com/Wengier/dosbox-x-wiki/wiki/images/MS-DOS:MS-DOS_4.01_INSTALLER6.png
https://github.com/Wengier/dosbox-x-wiki/wiki/images/MS-DOS:MS-DOS_4.01_INSTALLER7.png
https://github.com/Wengier/dosbox-x-wiki/wiki/images/MS-DOS:MS-DOS_4.01_INSTALLER8.png
https://github.com/Wengier/dosbox-x-wiki/wiki/images/MS-DOS:MS-DOS_4.01_INSTALLER9.png
https://github.com/Wengier/dosbox-x-wiki/wiki/images/MS-DOS:MS-DOS_4.01_INSTALLER_FINISHED.png

**Comment by rderooy** [comment]
@Wengier I have started to directly push changes to the wiki using git. This should solve the issue where we get out of sync. And I can also add/update images. I have just added a Guide page for Windows 1.0x as a test.

**Comment by Wengier** [comment]
@rderooy Glad to hear that. I will resume working on the Wiki too to prepare for the next release of DOSBox-X.
