### ISSUE TITLE
Wiki page renamed

### ISSUE THREAD

**Issue by Wengier** [Wengier/dosbox-x-wiki#3]
I have renamed the Wiki page for the DOS installation guide from "Guide:MS-DOS" to "Guide:DOS Installation in DOSBox‐X" to better reflect its contents. Also changed the name "PC-DOS" to "PC DOS" in relevant pages because the latter is the official name of IBM's DOS (in contrary to Microsoft's "MS-DOS" which has a hyphen).

**Comment by rderooy** [comment]
I was actually converting the pages to AsciiDoc. MarkDown is too limited, it cannot even generate a TOC.

As to "PC DOS", IBM did not use that until PC DOS 6.10. Up to that point it was called "IBM DOS", or "Personal Computer DOS", which did get abbreviated in the media to PC DOS.

As reported by DOS itself when booting, or in later versions with the VER command:
- IBM Personal Computer DOS 1.00
- IBM Personal Computer DOS 1.10
- IBM Personal Computer DOS 2.00
- IBM Personal Computer DOS 2.10
- IBM Personal Computer DOS 3.00
- IBM Personal Computer DOS 3.10
- IBM Personal Computer DOS 3.20
- IBM Personal Computer DOS 3.30
- IBM DOS 4.00
- IBM DOS 5.00
- PC DOS 6.10
- PC DOS 6.30
- PC DOS 7.00

PC DOS 2000 was only used on the packaging, as it identifies itself as PC DOS 7.00 revision 1.

**Comment by Wengier** [comment]
@rderooy It is interesting that PC DOS 2000 identifies itself as “PC DOS 7.0” even during the setup. I guess some users may wonder why they got PC DOS 7.0 instead of PC DOS 2000 (which they intended) in such case :)

**Comment by rderooy** [comment]
Indeed. It was clearly a marketing thing. PC DOS 2000 is basically just PC DOS 7 with a few fixes, which I think where also available for download. If you already had PC DOS 7 you would probably feel a bit mislead into buying an update...
