### ISSUE TITLE
"BOOT A:" or "BOOT C:" is now supported

### ISSUE THREAD

**Issue by Wengier** [Wengier/dosbox-x-wiki#4]
I have seen that in a few Wiki pages commands like "BOOT -L A" and "BOOT -L C" are used. But in the recent DOSBox-X builds you can directly use "BOOT A:" or "BOOT C:" to boot from drive A or C, which should be much easier to remember and type.

**Comment by Wengier** [comment]
Also, the following IMGMOUNT command:

```IMGMOUNT A DISK.IMG -U```

It is equivalent to the two IMGMOUNT commands below:

```IMGMOUNT A -U```
```IMGMOUNT A DISK.IMG```

So you can use just one command instead of two.

**Comment by rderooy** [comment]
Thanks. I will update the pages probably tomorrow.

Not sure about using the combined mount/unmount as it may cause confusion.

**Comment by Wengier** [comment]
@rderooy ```IMGMOUNT A DISK.IMG -U``` basically means to mount DISK.IMG as A:, and in the mean time unmount any previous image if necessary. Hence it is a matter of convenience (so that there is no need to unmount it via a separate command first).

**Comment by rderooy** [comment]
@Wengier that is what I meant with a combined mount/unmount :-) I understood that your both unmounting and mounting in one command.

**Comment by Wengier** [comment]
@rderooy I guess perhaps it is fine to use separate mount/unmount commands when there are not so many disk images to swap, because a combined mount/unmount command will likely not save too much typing in this case, and there will be no possible confusion to cause. But for a lot of disk images, such as in the case of making PC DOS 2000 disk images using LOADDSKF, a combined mount/unmount commands will save a lot of keystrokes. So I have now changed the commands in the PC DOS 2000 install page from:

```
 IMGMAKE DISK1.IMG -t fd_1440
 IMGMOUNT A DISK1.IMG
 LOADDSKF PCDOS_1.DSK A:
 MOUNT A -U
 IMGMAKE DISK2.IMG -t fd_1440
 IMGMOUNT A DISK2.IMG
 LOADDSKF PCDOS_2.DSK A:
 MOUNT A -U
 IMGMAKE DISK3.IMG -t fd_1440
 IMGMOUNT A DISK3.IMG
 LOADDSKF PCDOS_3.DSK A:
 MOUNT A -U
 IMGMAKE DISK4.IMG -t fd_1440
 IMGMOUNT A DISK4.IMG
 LOADDSKF PCDOS_4.DSK A:
 MOUNT A -U
 IMGMAKE DISK5.IMG -t fd_1440
 IMGMOUNT A DISK5.IMG
 LOADDSKF PCDOS_5.DSK A:
 MOUNT A -U
 IMGMAKE DISK6.IMG -t fd_1440
 IMGMOUNT A DISK6.IMG
 LOADDSKF PCDOS_6.DSK A:
 MOUNT A -U
```
To:

 
```
 IMGMAKE DISK1.IMG -t fd_1440
 IMGMOUNT A DISK1.IMG -U
 LOADDSKF PCDOS_1.DSK A:
 IMGMAKE DISK2.IMG -t fd_1440
 IMGMOUNT A DISK2.IMG -U
 LOADDSKF PCDOS_2.DSK A:
 IMGMAKE DISK3.IMG -t fd_1440
 IMGMOUNT A DISK3.IMG -U
 LOADDSKF PCDOS_3.DSK A:
 IMGMAKE DISK4.IMG -t fd_1440
 IMGMOUNT A DISK4.IMG -U
 LOADDSKF PCDOS_4.DSK A:
 IMGMAKE DISK5.IMG -t fd_1440
 IMGMOUNT A DISK5.IMG -U
 LOADDSKF PCDOS_5.DSK A:
 IMGMAKE DISK6.IMG -t fd_1440
 IMGMOUNT A DISK6.IMG -U
 LOADDSKF PCDOS_6.DSK A:
 IMGMOUNT A -U
```

**Comment by rderooy** [comment]
Just a thought... Would it not be better to automatically unmount if you're
mounting on a drive letter that already has a mount? So no need to use -u?

**Comment by Wengier** [comment]
> Just a thought... Would it not be better to automatically unmount if you're mounting on a drive letter that already has a mount? So no need to use -u?
> […](#)

I think that can be an option, but I don't think it should be the default behavior, because in such case a new MOUNT/IMGMOUNT command will override any existing mounting, which may be accidental and not expected, and could cause incompatibility with the existing code.

**Comment by Wengier** [comment]
@rderooy You can just use "ver = 7.1" (or ```VER SET 7.1```) instead of "ver = 7.10"  (or ```VER SET 7.10```) for DOS 7.1. I have modified the Wiki page to use the simpler method instead.
