### ISSUE TITLE
New release of DOSBox-X

### ISSUE THREAD

**Issue by Wengier** [Wengier/dosbox-x-wiki#6]
I am very glad to see the new DOSBox-X 0.83.2 version, which has so many new features added. At the same time, the current contents in this Wiki is already targeted for the DOSBox-X 0.83.2 version. I am ready to see it merged to the official Wiki, and if @rderooy has also finished editing its content, I believe @joncampbell123 can go ahead and merge it.

**Comment by joncampbell123** [comment]
The latest commit here is from April 8th. Is that what should be merged into DOSBox-X's wiki?

**Comment by rderooy** [comment]
I'm fine with merging.

**Comment by rderooy** [comment]
No. The actual wiki pages themselves need merging.

**Comment by joncampbell123** [comment]
Hm? What do I pull and merge from then?

**Comment by rderooy** [comment]
Good question.

I think if I recall correctly that you can clone or pull the wiki
separately with an additional /wiki at the end.

**Comment by joncampbell123** [comment]
I get it now, branch dosbox-x-wiki.wiki to pull from the Wiki section. Right?

**Comment by rderooy** [comment]
$ git clone https://github.com/*YOUR_USERNAME*/*YOUR_REPOSITORY*.wiki.git
# Clones the wiki locally

**Comment by joncampbell123** [comment]
Got it. Sorry, tired tonight.

**Comment by rderooy** [comment]
@joncampbell123 reminder, could you pull the latest wiki updates?

**Comment by joncampbell123** [comment]
@rderooy Done. Sorry for the long delay, my professional work required me to spend the last few days getting our Linux from Scratch system to compile newer versions of GCC, glibc, and binutils, which is way harder than it sounds. :)

**Comment by Wengier** [comment]
@joncampbell123 I see, and I think this now applies to me too. I am very happy to focus on improving DOSBox-X, but my professional work now required me to spend more time on it. I have been glad to work on projects like this.

**Comment by joncampbell123** [comment]
Case in point... glibc 2.30 suddenly requires Python 3.x to compile. Argh...

Understand glibc is THE core C runtime of the Linux system that everything else relies on. Getting it to bootstrap to build an entire system, including the "multilib" 32/64-bit combined lib/lib64 system we build, is a lot of work.

i686 and x86_64, of course.

**Comment by joncampbell123** [comment]
@Wengier What about your professional work involves DOSBox-X? Just curious.

**Comment by joncampbell123** [comment]
Just to clarify, DOSBox-X is a fun hobby project I do in my spare time. My professional work involves TV broadcast software, which I have been developing on Linux and marketing since 2006. That means writing code to work with MPEG files, rendering, decoding, encoding, and even getting Black Magic's Decklink SDK to cooperate for clients that need SDI/HD-SDI connections. This is all built on a Linux from Scratch system I've built up from source.

**Comment by joncampbell123** [comment]
The other reason for the bump in GCC, etc. is that the newer GCC versions (in this case 9.3) have a lot of useful warnings and features that can aid in development of DOSBox-X that GCC 4.8.5 does not have. DOSBox-X benefits too.

**Comment by Wengier** [comment]
@joncampbell123 I want to clarify too that my professional work has nothing to do with DOSBox-X. It is also a hobby contribution I do in my spare time. I simply meant that my employer now wants me to spend more time on the professional work, so I will have less spare time to work on projects like DOSBox-X and DOSBox-staging (I have been working on both recently indeed). My professional work involves management systems coded with PHP and website building with HTML/JavaScript, so it is far away from the main language used by DOSBox-X and DOSBox-staging, which is C++.

**Comment by joncampbell123** [comment]
@Wengier Heh, PHP... up until version 4 of our product, the web interface presented by the server unit was backed by PHP and HTML. Except in version 1, when I took a serious attempt at building a web interface in Perl Mason. That was fun.

You know how you can put PHP inline to the HTML? Perl Mason does the same, but it's Perl inline to the HTML page.

It actually worked pretty well, it was just rather annoying to have to restart Apache to see your latest changes because the Mason module was so aggressive at caching.

**Comment by joncampbell123** [comment]
Our latest web interface now is an odd mix of C++ (by me) and Node JS (by my dev team), so that's rather interesting to maintain.

**Comment by Wengier** [comment]
@joncampbell123 I think PHP is a somewhat higher level language than C/C++, so you don't have to often implement functions on your own in many cases as in C/C++. JavaScript also has this advantage in many cases (NodeJS is just JavaScript on the server side). These languages are more web-oriented than C/C++, so they are often desired to put inline to the HTML. For example,

``<?php echo "Hello";?>``

Very easy. I have not worked with Perl Mason yet, but it is good that you know such languages.

On the other hand, C/C++ is more hardware-oriented, so that is why it is a better language to make DOS emulators etc.

**Comment by Wengier** [comment]
@joncampbell123 I was a great fan of DOS, using DOS as the main OS for many years even in the 2000s and created several DOS websites. But in the recent years I have gradually switched to Windows as the main OS after all, so I decided to work on DOS emulators instead and have great passion on it. So C/C++ also becomes the main language for me to use in my spare time.

**Comment by joncampbell123** [comment]
I am a great fan of DOS because it's a great way to learn how to program the hardware. While it's no longer my primary OS, it's still a good OS to play with at that level.

**Comment by Wengier** [comment]
I am a great fan of DOS primarily because it is fast and clean, and I also love the environments I used to work with such as GW-BASIC and more. For example, Windows 9x/ME/XP at that time was very slow to load and also crashed a lot, but DOS is much faster to start compared to them.

But I am also very interested to make DOS work with newer hardware, such as FAT32, AC97, USB etc, so that is why I promoted things like MS-DOS 7.1, USBASPI, etc at that time. For example, the standalone installable version of MS-DOS 7.1 was made by me (and my coworker):

https://winworldpc.com/product/ms-dos/7x

It was released in the name of CDU (China DOS Union), which I created in the early 2000s as a union of several DOS websites. We published many DOS software in the name of CDU at that time, although most if them were for Chinese-language users. But in recent years I have been working more towards English-language users, and more active in English-language forums.

**Comment by Wengier** [comment]
You can see some screenshots of the MS-DOS 7.1 installable package from:

http://www.cn-dos.net/msdos71/scrshot.htm

**Comment by rderooy** [comment]
@joncampbell123 assuming @Wengier has no issues, can you pull an update for the Wiki?

p.s. Is there a problem with the RPM builds? As I see there is no Linux binary release up to now.

**Comment by Wengier** [comment]
@joncampbell123 and @rderooy Yes, the Wiki content is now targeted for DOSBox-X 0.83.4 and ready to be pulled.

**Comment by Wengier** [comment]
@rderooy I think @joncampbell123 is still busy building Linux RPM packages at this time. Right now I can already see the CentOS 7 packages in the Releases page.

**Comment by joncampbell123** [comment]
I'm having difficulty building the Centos 8 image because Centos 8 is suddenly unable to talk to my laptop's wireless card. It keeps loading and unloading for some reason.

**Comment by joncampbell123** [comment]
I'm going to have to skip Centos 8 this month until it figures out how to speak Wi-Fi again. It's not the card. Centos 7, Windows 10, and my own Linux From Scratch system on the same laptop work with Wi-Fi just fine.

**Comment by Wengier** [comment]
The all-in-one Windows installer for DOSBox-X 0.83.4, based on the @joncampbell123's released Windows binaries intact, is now available below, which has again been code-signed by Edward Mendelson:

https://github.com/Wengier/dosbox-x-wiki/raw/master/DOSBox-X-0.83.4-setup.exe

Or from:

https://github.com/Wengier/dosbox-x-wiki/raw/master/DOSBox-X-Setup-Windows-latest.exe

**Comment by Wengier** [comment]
@joncampbell123 Could you please merge the updated documentation? The current doc still lists DOSBox-X 0.83.3 as the latest version, which I have already updated to reflect the recent release of 0.83.4. Thanks a lot!

**Comment by Wengier** [comment]
@joncampbell123 By the way, I have again posted the new DOSBox-X version in the forum, like this one:

https://www.reddit.com/r/emulation/comments/i388n5/dosboxx_0834_released_with_windows_installer/

**Comment by joncampbell123** [comment]
Sorry about that... merged.

**Comment by Wengier** [comment]
Thanks @joncampbell123.

**Comment by Wengier** [comment]
@joncampbell123 Could you please merge the pull request joncampbell123/dosbox-x#1782 too? In addition to new features, it includes updates to the documentation files INSTALL.md etc to list DOSBox-X 0.83.4 files instead of the previous 0.83.3 files, and I have already finished the code changes for today. Thanks!

**Comment by joncampbell123** [comment]
@Wengier Done. I fixed your slot management code to compile with GCC. Apparently even if you use a C++ class to define the class and an instance, the name of the instance is not valid within the C++ class body. It's unlikely I broke the code in any way but please do check.

**Comment by Wengier** [comment]
@joncampbell123 Thanks! After I make changes to the code I usually compile the code in Visual Studio (SDL1 and SDL2), MinGW 64-bit, and sometimes also open VMware Workstation to test it in Linux/GCC. But it is also true that sometimes due to lack of time I could not test the new code in all of these platforms, especially Linux/GCC because opening VMware Workstation slows the whole system down significantly. I think the current code should work, but by looking at the code it seems that the added “GetCurrentSlot()” function does exactly the same thing as the existing “GetGameState()” function, so I will probably modify the code to use the existing function instead.

**Comment by Wengier** [comment]
@joncampbell123 I think pull request joncampbell123/dosbox-x#1795 is ready to be merged now. I have tested the code in Visual Studio (SDL1 & SDL2), MinGW 64-bit, as well as Linux/GCC to confirm the code works.

**Comment by joncampbell123** [comment]
@Wengier Got it. Do you get compiler warnings for glide.cpp on your end? GCC 9.3 has some comments about unused parameters and signed/unsigned compares.

**Comment by Wengier** [comment]
@joncampbell123 Thanks! I think I did see some compiler warnings for the file glide.cpp previously, which I believed are the usual warnings (like signed/unsigned compares you mentioned). I am unable to verify it right now because I am now away from my main computer, but I will be able to verify it tomorrow.

**Comment by Wengier** [comment]
@joncampbell123 I have checked and can confirm there are indeed warnings from GCC regarding unused parameters and signed/unsigned compares in the file glide.cpp. On the other hand, the part of Glide code that triggered such warnings was ported from DOSBox ECE without modifications, so the code should work as is, but it is possible to also silence these warnings of course.

**Comment by joncampbell123** [comment]
@Wengier They can be silenced with some typecasting, pretty easy. I made a commit last night to silence GCC's complaint about operator precedence without parenthesis (&& vs ||). I think that's code you wrote, could you check to make sure I didn't break it?

I based the change on GCC's warning and a list of C++ operator and their precedence. && takes higher precedence than || according to the list.

**Comment by Wengier** [comment]
@joncampbell123 That line in the bios file was indeed my code. When I studied C++ in the very beginning, I learned that among its operators && takes higher precedence than ||, so if it is to be the expected behaviour I often did not put parentheses in the code, assuming everyone knows this precedence rule. Much later I became aware that GCC would warn about it..

**Comment by Wengier** [comment]
@joncampbell123 I can understand that you are pretty frustrated with VS2019 on your computer. But the VS2019 binaries I built are available from here:

[dosbox-x-windows-20200901-110708-windows.zip](https://github.com/Wengier/dosbox-x-wiki/raw/master/dosbox-x-windows-20200901-110708-windows.zip)

And the Windows installer that includes both VS2019 x86/x64/ARM/ARM64 binaries above and MinGW32/64 binaries you built is available from:

[DOSBox-X-0.83.5-setup.exe](https://github.com/Wengier/dosbox-x-wiki/raw/master/DOSBox-X-0.83.5-setup.exe)

If you are fine with them, you can add them to the Releases page as well.

**Comment by joncampbell123** [comment]
@Wengier It's pretty simple: I booted up Windows 10 and VS2019 last night to compile... and it threw a bunch of bizarre COM errors loading the project. So I uninstalled it entirely and skipped that build step. If it doesn't want to work when I go to use it, then I don't care to waste my time with it.

I have no idea what caused it. Anything could have done it... even a feature update of Windows 10.

Later this month I'll take the time to see if VS2020 (is that out yet?) does a better job.

**Comment by Wengier** [comment]
@joncampbell123 Sure. It seems MS screws up things sometimes, even for GitHub. Let's see how VS2020 works then.

**Comment by Wengier** [comment]
@rderooy I think the current Wiki content is already ready for DOSBox-X 0.83.5. Are you okay with the Wiki content?

**Comment by Wengier** [comment]
@joncampbell123 I have found that the website http://dosbox-x.com/ (which supposed to be the DOSBox-X homepage) does not appear to be very developed. For example, the link under "Documentation" does not have any actual documentation, and the page under "Development and testing" only has placeholder contents from long time ago. I have seen users from e.g. the Vogons forums who visited http://dosbox-x.com/ saying that they could not find the information they need from that page (they seem to be also unable to find the link to the GitHub site, which does not appear to be very noticeable for them). I think the DOSBox-X documentations have been significantly developed in recent months, but the website http://dosbox-x.com/ has not been updated for a while. Are you interested in improving the content of this website to make it look better? If you do, I am glad to refine/expand it similar to what I have done to the Wiki and GitHub README.md etc, adding more content including some nice screenshots to make it look more developed and attract users. The website and Wiki etc each have their different functions of course.

**Comment by rderooy** [comment]
@Wengier @joncampbell123 Yes I'm fine with the wiki content for now.

**Comment by Wengier** [comment]
@joncampbell123 An example website I am looking at is the QEMU website (https://www.qemu.org/). But it is just an example so it is completely fine to look for another design that is more fitted to DOSBox-X of course.

**Comment by joncampbell123** [comment]
@Wengier I'm going to be fairly busy in the next months. I will be refactoring code at work and working on something for the DOS games jam this fall. If you like I could add you as a collaborator to DOSBox-X to help smooth out development.

dosbox-x.com is controlled by the gh-pages branch. Anything in that branch appears on the site.

**Comment by Wengier** [comment]
@joncampbell123 I see. And thank you for the invitation! I am very happy to make every effort to help improve the DOSBox-X project as a whole, including improvements to the code, documentation, and website.

**Comment by Wengier** [comment]
Thanks! I have found the HTML page. I will make efforts to improve it very soon.

https://github.com/joncampbell123/dosbox-x/blob/gh-pages/index.html

**Comment by Wengier** [comment]
I see that I can now add labels to issues in the issue tracker, so I will try to do this as well to make issues there more organized.

**Comment by Wengier** [comment]
@joncampbell123 DOSBox-X is a fork of DOSBox (of course), but **for advertising purpose** it is probably better to say that it is a "cross-platform DOS emulator based on the DOSBox project" or so. That is why I tried to make change to that wording some time ago.

**Comment by Wengier** [comment]
@joncampbell123 and @rderooy I have already tried to update the https://dosbox-x.com/ website today. I primarily use Google Chrome to develop the site, but I also checked it on Firefox, Opera and Microsoft Edge on my computer. More information can be added to the site later on of course. Please let me know if you find any issues. Thanks.

**Comment by rderooy** [comment]
@Wengier nice! 

The only thing I don't really like are the screenshots which are being stretched to fit the browser width. Even on a regular 16/9 monitor they are already clearly stretched, and I suspect that if I where to load it on my son's ultra-wide it would just stretch it out to ridiculous proportions.

**Comment by joncampbell123** [comment]
@rderooy There is a setting and a menu item to control whether the DOS screen is scaled to fit according to it's aspect ratio.

**Comment by rderooy** [comment]
@joncampbell123 I was talking about the screenshots on the dosbox-x.com website :-)

**Comment by Wengier** [comment]
@rderooy and @joncampbell123 Thanks for the suggestions! I have retaken most screenshots with the aspect ratio correction mode this time and hopefully they will look better. Make sure to refresh the images when re-loading the website.

**Comment by Wengier** [comment]
@joncampbell123 The website domain http://dosbox-x.com (or https://dosbox-x.com/) works well, but I found that the domain (http://www.dosbox-x.com/ (or https://www.dosbox-x.com/) (that is, with "www.") simply does not work. Could you enable the “www” subdomain in the settings as well? Thanks!

Some information on setting up the GitHub domain can be found here:

https://medium.com/@hossainkhan/using-custom-domain-for-github-pages-86b303d3918a

**Comment by Wengier** [comment]
@joncampbell123 You can enable the “www” subdomain when you have time to look at it of course. Thanks!

**Comment by Wengier** [comment]
@joncampbell123 I indeed did not quite finish the section change last night. For example, I modified the Windows installer to automatically move such settings to the new section while keeping user settings today (so that DOSBox-X won't even need to auto-redirect them). Everything else related to this change should be done today.

**Comment by Wengier** [comment]
@joncampbell123 I realized I should had asked you about the dosbox-x.software domain beforehand. But I have now added it too, including places like the project README and Wiki, which never mentioned beforehand.

**Comment by Wengier** [comment]
@joncampbell123 I also want to mention that when my focus switched from vDosPlus to DOSBox, I had indeed made serious efforts to try to get used to this new development system over the last a few months. For example, I am now pretty much used to cross-platform development (instead of typically calling Windows-only functions as done previously). Also, I am very very happy about DOSBox-X’s flexibility (support for various options), the idea of complete DOS emulation package, support for Win3.x/9x etc. I also like the general idea of implementing more accurate emulation, for example, the DOS shell commands I implemented or improved over the last a few months (e.g. ATTRIB, DIR, DEL, DELTREE, FOR, REN, etc) all tried to follow (or make them follow) the original behaviours of the MS-DOS counterparts, instead of either not implementing them properly or making unnecessary “fancy” stuff in these shell commands. All in all, DOSBox-X is an excellent project, and I really enjoyed it and seriously hoped others to join and use it as well.

For the purpose of advertisement, I tried to also label DOSBox-X as “a complete DOS emulation package that is both fully-featured and easy to use” (in addition to “it is our desire to maintain and implement more accurate emulation”) in the homepage so that it will hopefully attract more users (as an aside, DOSBox-X is indeed more fully-featured and easier to use than similar projects, so the sentence is not really wrong). I had personally seen multiple times previously that users saying something like “DOSBox-X focuses on accuracy, try other alternatives instead”. Accuracy is very important for DOSBox-X of course (in addition to completeness etc), and in my opinion the more accurate the better, and i think I had been trying to follow it myself, but I also thought that stating it in that way to outsiders (something like “DOSBox-X focuses on accuracy”) can make some users leave without even trying it, so I tried to make it read something like “a complete and accurate DOS emulation package" instead in the hope that it more appealing to other users. All these are primarily for advertising purpose so that more users will likely enjoy the software (I think you had really done wonderful work in developing DOSBox-X in the last a few years, and more users should be using it really). But such wording (for the purpose of marketing) does not intend to change the actual status of the project in any way, as we all still try to follow our project principles as before. What do you think? Thanks!

**Comment by joncampbell123** [comment]
It should work now.

Although it doesn't make any sense to me. Both dosbox-x.com and dosbox-x.software had * and (empty) DNS host entries which *should* include www as well.

**Comment by Wengier** [comment]
@joncampbell123 Yes, I can confirm that http://www.dosbox-x.com/ now works, which is great. Thanks!
