### ISSUE TITLE
New Wiki pages split from the welcome page

### ISSUE THREAD

**Issue by Wengier** [Wengier/dosbox-x-wiki#8]
I have now split the following Wiki pages from the welcome page with some added information. The welcome page is now shorter and more focused because of this. The new Wiki pages are:

* [DOSBox‐X’s Feature Highlights](https://github.com/Wengier/dosbox-x-wiki/wiki/DOSBox%E2%80%90X’s-Feature-Highlights)

* [DOSBox‐X’s GUI Menus](https://github.com/Wengier/dosbox-x-wiki/wiki/DOSBox%E2%80%90X’s-GUI-Menus)

* [DOSBox‐X’s Supported Commands](https://github.com/Wengier/dosbox-x-wiki/wiki/DOSBox%E2%80%90X’s-Supported-Commands)

* [DOSBox‐X’s Command line Options](https://github.com/Wengier/dosbox-x-wiki/wiki/DOSBox%E2%80%90X’s-Command-line-Options)

**Comment by rderooy** [comment]
Nice. That makes it feel less cluttered.

**Comment by rderooy** [comment]
It is really annoying that the wiki pages (and also lots of other github pages like issues, pr's, etc) are being deliberately blocked from being indexed by Google and other search engines by means of the https://github.com/robots.txt file. Making it much more difficult for people to find the content.

**Comment by Wengier** [comment]
Are you aware of any possible solution to the said issue?

**Comment by rderooy** [comment]
There are just two

- Github removes the block, but people have been complaining about it for years without success
- Move to a different wiki service that does allow indexing

I suspect they block it, to prevent the wiki becoming a spamming target.

**Comment by Wengier** [comment]
A suggestion: if a (sub)domain like http://wiki.dosbox-x.com/ is created which redirects to the existing Wiki system transparently, will it allow indexing?

**Comment by rderooy** [comment]
good question. This seems to suggest that it would work:
https://support.google.com/webmasters/thread/15332085?hl=en

As long as there is no robots.txt file on wiki.dosbox-x.com blocking access.

**Comment by Wengier** [comment]
It is only my suggestion (which will make the Wiki URL easier to remember as well). Only @joncampbell123 can actually create such subdomains.

**Comment by rderooy** [comment]
So after the wiki was moved to https://dosbox-x.com/wiki/ the main wiki page has been indexed by Google. But the sub-pages are not, and I don't understand why. There is no issue with https://dosbox-x.com/robots.txt

**Comment by Wengier** [comment]
@rderooy I am not really sure about the reason either. Maybe because of the frame? But this is only a guess.

P.S. DOSBox-X 0.83.8 is now released. I think a new Linux Flatpak can be made for it. If you have time, you can update the main screenshot too since I was not able to take the screenshot of that size here.

**Comment by rderooy** [comment]
@Wengier I had already created a new flatpak.

I will see if I have a moment to update the screenshot, and perhaps add another screenshot or two. Perhaps one with Windows 3.1 and one with something like 123, WP or Word for DOS. Perhaps even with TTF.
