### ISSUE TITLE
Windows 98 installation freezes(never mind)

### ISSUE THREAD

**Issue by jadasse** [Wengier/dosbox-x-wiki#9]
When installing windows 98, after the setup copies the files and I reboot, it will detect the plug and play hardware and it will freeze forever, what do I do? Am I impatient? I made a copy of the img to save progress so I don't have to start over.

**Comment by jadasse** [comment]
By the way, is it possible to install windows 98 through a directory on my computer instead?

**Comment by jadasse** [comment]
Never mind

**Comment by rderooy** [comment]
so this issue can be closed?

Oops, missed the follow-on email that it already was closed.
